### ISSUE TITLE
  throw er; // Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by reverland** [HalfdogStudio/wechat-user-bot#45]
what a fuck~can't I just capture error in stream with try...catch?
```bash
info: [邱神与大家分享人生的jy]んS:已举报<span class="emoji emoji1f510"></span>
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1076:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
```

**Comment by reverland** [comment]
yeah, a 'error' event handler must be added here
